application:
  title: IMusic
  admin_title: Admin IMusic
  admin: admin
user:
  name:
    max_length: 50
track:
  featured_list: 3
  title:
    max_length: 30
  year:
    minimum: 0
    start: 1800
album:
  featured_list: 8
  name:
    max_length: 70
  year:
    minimum: 0
    start: 1800
category:
  featured_list: 8
  name:
    max_length: 30
artist:
  featured_list: 4
  start_year: 1800
  name:
    max_length: 50
  country:
    max_length: 50
min_friendly_token: 0
max_friendly_token: 20
omniauth:
  facebook: facebook
  google_oauth2: google_oauth2
